name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-4-dev \
          libgdk-pixbuf-2.0-dev \
          libglib2.0-dev \
          libgio2.0-dev \
          libpng-dev \
          libjpeg-dev \
          libtiff-dev \
          pkg-config \
          build-essential

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose 